444version: '3.7'
services:
  ainomo:
    build:
      context: ./docker/ainomo/
      args:
        - ARAGON_DEFAULT_ETH_NODE=ws://34.159.167.0:8546
        - ARAGON_APP_LOCATOR=ipfs
        - ARAGON_ETH_NETWORK_TYPE=local
        - ARAGON_ENS_REGISTRY_ADDRESS=0xD1A23B83902066baC61e82bCe449fE1d3154Ab5D
    container_name: ainomo
    ports:
      - 3000:8080
