version: '3.7'
services:
  eth:
    build:
      context: ./docker/geth/
    container_name: eth
    ports:
      - 8545:8545
      - 8546:8546
    environment:
      - NETWORK_ID=1337

  ipfs:
    image: ipfs/go-ipfs:latest
    container_name: ipfs
    ports:
      - 5001:5001
      - 8080:8080

  ainomo:
    build:
      context: ./docker/ainomo/
      args:
        - AINOMO_IPFS_GATEWAY=http://localhost:8080/
        - AINOMO_DEFAULT_ETH_NODE=ws://localhost:8546
        - AINOMO_APP_LOCATOR=ipfs
        - AINOMO_ETH_NETWORK_TYPE=local
    container_name: ainomo
    ports:
      - 3000:8080
